FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["./Report/PsychologicalSupportPlatform.Report.API/PsychologicalSupportPlatform.Report.API.csproj", "Report/PsychologicalSupportPlatform.Report.API/"]
COPY ["./PsychologicalSupportPlatform.Common/PsychologicalSupportPlatform.Common.csproj", "PsychologicalSupportPlatform.Common/"]
COPY ["./Report/PsychologicalSupportPlatform.Report.Application/PsychologicalSupportPlatform.Report.Application.csproj", "Report/PsychologicalSupportPlatform.Report.Application/"]
COPY ["./Report/PsychologicalSupportPlatform.Report.Domain/PsychologicalSupportPlatform.Report.Domain.csproj", "Report/PsychologicalSupportPlatform.Report.Domain/"]
COPY ["./Report/PsychologicalSupportPlatform.Report.Infrastructure/PsychologicalSupportPlatform.Report.Infrastructure.csproj", "Report/PsychologicalSupportPlatform.Report.Infrastructure/"]
RUN dotnet restore "Report/PsychologicalSupportPlatform.Report.API/PsychologicalSupportPlatform.Report.API.csproj"
COPY . .
WORKDIR "/src"
RUN dotnet build "Report/PsychologicalSupportPlatform.Report.API/PsychologicalSupportPlatform.Report.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Report/PsychologicalSupportPlatform.Report.API/PsychologicalSupportPlatform.Report.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "PsychologicalSupportPlatform.Report.API.dll"]
