version: '1.0'

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    ports:
      - 9200:9200 
    volumes: 
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - xpack.security.enabled=false
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node 
    networks:
      - platform
      
  kibana:
    container_name: kibana 
    image: docker.elastic.co/kibana/kibana:8.11.3
    ports:
      - 5601:5601 
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200
    networks:
      - platform
    
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    restart: unless-stopped
    volumes:
      - redis-data:/data/redis
    networks:
      - platform
        
networks:
  platform:
    name: platform
volumes:
  elasticsearch-data:
  redis-data:  